const { test } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const nbt = require('prismarine-nbt')
const { ensureServer } = require('../app/assets/js/serverlist')
test('adds public server once and preserves existing favourites and metadata', t => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'krwa-serverlist-'))
    t.after(() => fs.rmSync(dir, { recursive: true }))
    const original = nbt.comp({ servers: nbt.list(nbt.comp([{ name: nbt.string('Personal'), ip: nbt.string('example.test'), icon: nbt.string('custom-icon'), acceptTextures: nbt.byte(1) }])), custom: nbt.int(42) })
    const file = path.join(dir, 'servers.dat')
    fs.writeFileSync(file, nbt.writeUncompressed(original))
    assert.equal(ensureServer(dir, 'KRWA Create', 'create.krwa.ru:25565'), true)
    const after = nbt.parseUncompressed(fs.readFileSync(file))
    assert.deepEqual(after.value.servers.value.value[0], original.value.servers.value.value[0])
    assert.equal(after.value.custom.value, 42)
    assert.equal(ensureServer(dir, 'KRWA Create', 'create.krwa.ru'), false)
    assert.equal(after.value.servers.value.value.length, 2)
})
test('creates a fresh list and refuses to overwrite a corrupt list', t => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'krwa-serverlist-'))
    t.after(() => fs.rmSync(dir, { recursive: true }))
    ensureServer(dir, 'KRWA Create', 'create.krwa.ru')
    const file = path.join(dir, 'servers.dat')
    fs.writeFileSync(file, 'broken')
    assert.throws(() => ensureServer(dir, 'KRWA Create', 'create.krwa.ru'))
    assert.equal(fs.readFileSync(file, 'utf8'), 'broken')
})
